Documentation fix/simon 05042022 contracts
ApeWorX/web3.py pull request #2414
Opened 2022-04-05 16:16 UTC by lauwsj-alpha

### What was wrong?

Related to Issue #2386, Currently not all Ethereum nodes support signing transaction and it would be better to sign the transactions locally. 

### How was it fixed?

Replace all the `transact()` method with `send_raw_transaction` and also add example using `construct_sign_and_send_raw_middleware` for  `Greeter` programme

### Todo:
- [ ] Add entry to the [release notes](https://github.com/ethereum/web3.py/blob/master/newsfragments/README.md)

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://dynaimage.cdn.cnn.com/cnn/q_auto,w_727,c_fit/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F180302150409-cryptokitties-1.jpg)

2022-04-05 16:21 UTC, Jonjay2626 approved these changes

2022-06-29 20:12 UTC, fselmo requested changes
I apologize for how long it took to review this... there are a lot of comments here but it's mostly about using `snake_case` over `camelCase` in a few places so don't worry 😅.

I also posed a question on the `EthereumTesterProvider()` examples that I'm curious to hear thoughts on.

Thanks for taking this on... this is a great addition to keep our docs up-to-date 👍

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    >>> signed_transaction = my_account.signTransaction(tx_params)
```suggestion
    >>> signed_transaction = my_account.sign_transaction(tx_params)
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +       >>> tx_params = contract.functions.myFunction(12345).buildTransaction({
```suggestion
       >>> tx_params = contract.functions.myFunction(12345).build_transaction({
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +       >>> tx_params = contract.functions.myFunction(12345).buildTransaction({
```suggestion
       >>> tx_params = contract.functions.myFunction(12345).build_transaction({
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +       >>> signed_transaction = my_account.signTransaction(tx_params)
```suggestion
       >>> signed_transaction = my_account.sign_transaction(tx_params)
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    signed_transaction = alice_account.signTransaction(tx_params)
```suggestion
    signed_transaction = alice_account.sign_transaction(tx_params)
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    tx_params = my_token_contract.constructor(1000000).buildTransaction({
```suggestion
    tx_params = my_token_contract.constructor(1000000).build_transaction({
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    signed_transaction = alice_account.signTransaction(tx_params)
```suggestion
    signed_transaction = alice_account.sign_transaction(tx_params)
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    >>> tx_params = contract.functions.transfer(alice, 10).buildTransaction({
```suggestion
    >>> tx_params = contract.functions.transfer(alice, 10).build_transaction({
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    >>> signed_transaction = alice_account.signTransaction(tx_params)
```suggestion
    >>> signed_transaction = alice_account.sign_transaction(tx_params)
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +   >>> signed_transaction = my_account.signTransaction(tx_params)
```suggestion
   >>> signed_transaction = my_account.sign_transaction(tx_params)
```

2022-06-29 20:12 UTC, fselmo commented on docs/contracts.rst
> +    provider = Web3.EthereumTesterProvider()
Same thought as above on the `EthereumTesterProvider()`... do we just keep this simpler? This isn't a node and we don't need to tiptoe around anything by signing before sending to `eth-tester`. So should we keep the api simpler here? I can go either way but I think I lean towards the simpler setup.

2025-04-28 21:22 UTC, closed without merging